spring:
  threads:
    virtual:
      enabled: true
  profiles:
    group:
      "local": "localdb,common,localms"
      "dev": "devdb,common,devms"
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: "localms"
logging:
  level:
    root: info
  file:
    name: "./library-webapp.log"

---
spring:
  config:
    activate:
      on-profile: "devms"
logging:
  file:
    name: /data/logs/spring/${DB_NAME}/library-webapp.log

---
spring:
  config:
    activate:
      on-profile: "localdb"
  h2:
    console:
      enabled: true
      path: /h2/library
      settings:
        trace: true
  data:
    redis:
      port: 6379
      host: 127.0.0.1

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:library
      username: ether
      password: 1234
  jpa:
    database: h2
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath*:/schema.sql
      data-locations: classpath*:/data.sql

---
spring:
  config:
    activate:
      on-profile: "devdb"
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  datasource:
    hikari:
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:3306/${DB_NAME}?createDatabaseIfNotExist=true
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath*:/schema.sql
      data-locations: classpath*:/data.sql
      continue-on-error: true

---
spring:
  config:
    activate:
      on-profile: "common"
springfox:
  documentation:
    swagger:
      v2:
        path: "/swagger/docs/v2"
